### ISSUE TITLE
whether support sync mongo to kafka cluster?

### ISSUE THREAD

**Issue by sunweiconfidence** [rwynn/route81#2]
hi @rwynn,

i want to sync mongo replica set change stream to kafka cluster in one server 3 broker or 3 servers 3 broker, whether current version support it? if support, how to configure it? thank you very much.

**Comment by rwynn** [comment]
hi @sunweiconfidence, each route81 process is able to sync one mongodb cluster to one kafka cluster.  You can run as many route81 processes as you like if you need to support multiple clusters of each.  

You would configure each process like this...

```toml
mongo = "mongodb://[username:password@]host1[:port1][,...hostN[:portN]][/[database][?options]]"
kafka = "hostname:port,hostname2:port2,hostname3:port3"
```

And run with

```sh
route81 -f /path/to/config.toml
```
